Also check the custom element runtime file size

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -165,13 +165,22 @@ jobs:
         run: bun bin/prepareReleaseAssets.ts
       - name: List files
         run: ls -la ./dist
-      - name: Check file size
+      - name: Check runtime file size
         run: |
           FILE=./dist/page.main.esm.js
-          MAX_SIZE=102400
+          MAX_SIZE=122880
           ACTUAL_SIZE=$(stat -c%s "$FILE")
           if [ "$ACTUAL_SIZE" -gt "$MAX_SIZE" ]; then
-            echo "Error: $FILE is larger than 100KB ($ACTUAL_SIZE bytes)" >&2
+            echo "Error: $FILE is larger than 120KB ($ACTUAL_SIZE bytes)" >&2
+            exit 1
+          fi
+      - name: Check custom element runtime file size
+        run: |
+          FILE=./dist/custom-element.main.esm.js
+          MAX_SIZE=122880
+          ACTUAL_SIZE=$(stat -c%s "$FILE")
+          if [ "$ACTUAL_SIZE" -gt "$MAX_SIZE" ]; then
+            echo "Error: $FILE is larger than 120KB ($ACTUAL_SIZE bytes)" >&2
             exit 1
           fi
   test-assets-server:
